### ISSUE TITLE
To-do Milestone Roadmap

### ISSUE THREAD

**Issue by Sondro** [Freak613/1more#10]
Hi, is it possible to get a to-do milestone roadmap of missing features (maybe compared to ivi or React)?

It doesn't have to be super-detailed, just a list of some searchable terms so one can see what holes they may have to build around.

**Comment by Freak613** [comment]
It's easier to list what this library does instead of what is missing, which can be very long list, depending on what you comparing to. And it's already done in the README. 

If you considering using it and if README doesn't answers your questions then you'd better use more mature projects. This library in current state may only be used as-is by enthusiasts, as it requires time for anything unexpected.

When it will reach completeness, in some form, it will be released with major version 1.0.0. Then it may get more predictable development cycle.

**Comment by Sondro** [comment]
What's the ETA of 1.0?

Also, it doesn't make much sense for instance, to write your own router if you have one that's mostly done & is going to be added to the code base soon.

I want to port a non-trivial demo project to test.

It's not overly complex, but there are a variety of custom components (checkbox, input, radio, dropdown, forms, etc).

**Comment by Freak613** [comment]
Since this project is done in spare time it doesn't have any specific ETA for releases.

And since this project is in very early stage so API can be unstable and if you're going to use it be ready to lock version or to update code base for new releases.

I think it will be hard to implement all listed elements with proper UX at the moment, as library currently doesn't have refs and additional lifecycle hooks (like on mount).
