### ISSUE TITLE
Derived getters

### ISSUE THREAD

**Issue by mrjjwright** [Freak613/1more#3]
I have been studying this lib and there are several things I really like about it, in general it seems highly flexible with a great set of underlying decisions.   I use Sinuous and have built some custom elements on top of them and am in general happy but I am always looking for things that truly are more primitive, solid and flexible.   One thing that intrigues me is your little boxed observable implementation.   Why did you use linked lists (why does it make for an efficient observable mechanism) and how does one think about building derivations from higher level observables.  In particular what exactly is the mental model being used e.g. here?  

https://github.com/Freak613/1more/blob/109e69e29ed2461d32bb0eaa186529f467650cb2/examples/todomvc-optimized/app.js#L144

I am used to the mental model of computed in Mobx, S.js, Sinuous, sometimes called derivations, where derived functions automatically update from higher level observables on which they depend.   Is something subtly different going on here because of the linked list implementation, if so I am interested to compare.

**Comment by Freak613** [comment]
To note, I'm looking to remove `box` and its utils from the library, because they do not provide value in benchmarks anymore and there is no need to keep it in the core of the library. So I would advice to not rely much on it currently. Probably I'll move them into separate lib or provide link to replacement lib.

It is small because it is push-based observable implementation, like RxJS, i.e. it does not include autotracking and derivations from pull-push based systems like mobx. And it can have same problems as with any other push-observables lib like multiple triggering of subscriptions because of the lack of invalidation and scheduling mechanism, that libraries like mobx have.

As for linked lists, typically array supports 4 types of operation: Add, Remove, Lookup by index and iteration. And operation of removal (via filtering with new array instance) is slow because it require to shift a lot of elements in memory and has complexity O(n) because of iteration over all elements. New instance of array on removal is required in this case, because removal may be result of in-progress iteration over observables and modifying array in place will cause incorrect iteration order (some subs may be skipped because of their become shifted). Linked Lists have complexity for removal O(1), and can be modified in place without such issues. But instead their lookup is O(n) because of the need to iterate over all elements to find one with target index. Given the fact that for subscriptions list does not require lookup, they only need iteration and fast addition/removal, arrays can be replaced with linked lists and have performant removal for subscriptions list. This is completely implementation detail and does not affect user experience comparing with other push-observables lib.

As for mental model, it is one from RxJS observables. Whereas mobx-like libs setup and maintain subscriptions behind the scene, plain observables shift this burden to the user. And user should create/remove subscriptions manually when logic requires that. What being used in given example, is way to make `filteredTodos` observable react on both filter update, todos list update and todos flags change. For last point to work, actions push new value into `todos` observable even it does not have structural changes. 
So, no, it is not related to linked lists implementation, this is how push-based observables implementation can look like. And if you look into something simpler/smaller than `S.js` and like, probably this is not proper replacement. Yes, observables are simpler in implementation but their usability and problems with managing correct propagation order outweights this simplicity.

If you interested to understand what pull-push systems solve on top of plain observables, you can look into `S.js` test cases like this one, that show problem that push-observables can not solve:
https://github.com/adamhaile/S/blob/master/spec/S.spec.js#L143
Or if RxJS is something new to you, I'd advice to take a look on some online articles about it.

**Comment by mrjjwright** [comment]
Awesome answer, that was so helpful.    I have used push-pull observables for so long and never used rxjs style.  It sounds like I have avoided some problems for sure.   They really are awesome.  Thanks again, the linked list description is fascinating and I learned something for sure.    You, Ryan Cairnito, Adam Haile, Wesley Luyten, and the like are my heroes.

**Comment by mrjjwright** [comment]
I am using this with dipole (https://github.com/zheksoon/dipole), which was easy to integrate with your nifty `invalidate` call and it's working great!

**Comment by Freak613** [comment]
Yes, `invalidate` is a really nice thing, simplifying integrations with third-party libs, where in React it would require having `forceUpdate` state hook.

That's a nice lib! Fun fact, I'm going to publish something very similar soon, but coming from `S.js` implementation. I fixed some flaws of original (that I see this lib also have) related to correctness, memory consumption and performance. Also I'll drop the benchmark I'm using to measure and detect fixed problems, where I compare all major libs from this area (probably will have to add this lib also). I can let you know in this thread once it's done, if you interested.

**Comment by leeoniya** [comment]
:eyes:

**Comment by mrjjwright** [comment]
Oh that's freaking awesome!

**Comment by mrjjwright** [comment]
https://gist.github.com/mrjjwright/43d3ddf4830fb8d6bb3085b5652f9221

**Comment by Freak613** [comment]
@mrjjwright thanks! This gives me few ideas that I missed, like why reactions are needed when wiring reactive lib with renderer.

**Comment by mrjjwright** [comment]
Your lib, 1more, named the primitives that were needed to connect it with the primitives of Dipole.  `component`, `render`, `html`, `invalidate` meet `observable`, `computed`, `reaction`.    Special mention for how `invalidate` ties so nicely with the Dipole `reaction` scheduler, both of you seeing the need for this connection.   I notice this lib has a cleaner API than your previous work and Dipole also has an explicit clean straightforward API.   You both are talented library builders.
